source "https://rubygems.org"

# Specify your gem's dependencies in feature_user.gemspec.
gemspec

gem "puma"

gem "trilogy"

gem "propshaft"

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
