services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      EDITOR: vim
    tty: true
    stdin_open: true
    command: bundle exec rails s -b 0.0.0.0
  db:
    image: mariadb:11.7.2
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3377:3306
