source "https://rubygems.org"

# Specify your gem's dependencies in feature_review.gemspec.
gemspec

gem "puma"

gem "trilogy"

gem "propshaft"

group :development, :test do
  gem "factory_bot_rails"
  gem "rspec-rails"

  gem "debug", platforms: %i[mri windows], require: "debug/prelude"

  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end
